---
# This file is part of Ansible role geoffreyvanwyk.moodle_uninstall.
#
# Ansible role geoffreyvanwyk.moodle_uninstall is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Ansible role geoffreyvanwyk.moodle_uninstall is distributed in the hope that
# it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Ansible role geoffreyvanwyk.moodle_uninstall. If not, see
# <https://www.gnu.org/licenses/>.

##
# Contains specific tests against the state of the container after the role has
# finished executing.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Verify
  hosts: all
  gather_facts: false

  vars_files:
    - vars/main.yml
    - ../../vars/main.yml

  tasks:
    - name: Collect list of cron jobs
      ansible.builtin.command: crontab -l
      changed_when: false
      register: moodle_uninstall_cron_jobs

    - name: Assert that cron job does not exist
      loop: "{{ moodle_uninstall_cron_jobs.stdout_lines }}"
      ansible.builtin.assert:
        that: "{{ item is not search(moodle_deploy_destination) }}"

    - name: Collect list of databases
      become: true
      become_user: postgres
      community.postgresql.postgresql_info:
        filter:
          - "databases"
      register: moodle_uninstall_db

    - name: Assert that database does not exist
      ansible.builtin.assert:
        that: "{{
          moodle_cfg_dbname not in moodle_uninstall_db.databases.keys() }}"

    - name: Obtain status enabled Apache configuration
      ansible.builtin.stat:
        path: /etc/apache2/conf-enabled/{{ moodle_web_apache_conf }}
      register: moodle_uninstall_stat_enabled_apache_conf

    - name: Assert that enabled Apache configuration does not exist
      ansible.builtin.assert:
        that: not moodle_uninstall_stat_enabled_apache_conf.stat.exists

    - name: Obtain status available Apache configuration
      ansible.builtin.stat:
        path: /etc/apache2/conf-available/{{ moodle_web_apache_conf }}
      register: moodle_uninstall_stat_available_apache_conf

    - name: Assert that available Apache configuration does not exist
      ansible.builtin.assert:
        that: not moodle_uninstall_stat_available_apache_conf.stat.exists

    - name: Obtain status of Moodle source code directory
      ansible.builtin.stat:
        path: "{{ moodle_deploy_destination }}"
      register: moodle_uninstall_stat_deploy_destination

    - name: Assert that Moodle source code directory does not exist
      ansible.builtin.assert:
        that: not moodle_uninstall_stat_deploy_destination.stat.exists

    - name: Obtain status of moodledata directory
      ansible.builtin.stat:
        path: "{{ moodle_cfg_dataroot }}"
      register: moodle_uninstall_stat_moodledata

    - name: Assert that Moodledata directory does not exist
      ansible.builtin.assert:
        that: not moodle_uninstall_stat_moodledata.stat.exists
